// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZA5x229XaKg8x33fBr6UevpT_QorZie4',
    appId: '1:451852145416:web:78bff4d30384bb7d9112bd',
    messagingSenderId: '451852145416',
    projectId: 'my-ncds',
    authDomain: 'my-ncds.firebaseapp.com',
    storageBucket: 'my-ncds.firebasestorage.app',
    measurementId: 'G-V35K8YWPVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrEm0Vg1WGZC9Bv7bXssP3G9IfM9nM38c',
    appId: '1:451852145416:android:7828fe6267e3ab439112bd',
    messagingSenderId: '451852145416',
    projectId: 'my-ncds',
    storageBucket: 'my-ncds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-g406HmYey-Fh8d4HuMG4GvCjM_A0WM',
    appId: '1:451852145416:ios:b3334170d03c288f9112bd',
    messagingSenderId: '451852145416',
    projectId: 'my-ncds',
    storageBucket: 'my-ncds.firebasestorage.app',
    iosBundleId: 'com.example.projectncd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI-g406HmYey-Fh8d4HuMG4GvCjM_A0WM',
    appId: '1:451852145416:ios:b3334170d03c288f9112bd',
    messagingSenderId: '451852145416',
    projectId: 'my-ncds',
    storageBucket: 'my-ncds.firebasestorage.app',
    iosBundleId: 'com.example.projectncd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZA5x229XaKg8x33fBr6UevpT_QorZie4',
    appId: '1:451852145416:web:698ed9e7c051701a9112bd',
    messagingSenderId: '451852145416',
    projectId: 'my-ncds',
    authDomain: 'my-ncds.firebaseapp.com',
    storageBucket: 'my-ncds.firebasestorage.app',
    measurementId: 'G-QP1MTL32Z3',
  );
}
